### ISSUE TITLE
Binder link isn't work

### ISSUE THREAD

**Issue by moiseszeleny** [bradkav/WIMpy_NREFT#2]
Hi, this a very interesting repository but I tried to open binder link and does not work.

**Comment by bradkav** [comment]
Hi!

It looks like there was an issue with the requirements.txt file, which I've fixed now. The binder link should work now. Please let me know if it's working as expected and I'll close the issue :) 

Also the package should be pretty easy to install with pip (see the README) and there are plenty of notebooks in the Examples folder in case you want to go beyond just the binder example!

**Comment by moiseszeleny** [comment]
Now, binder link is running correctly and I will work with the examples. Thanks a lot
